spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tourneeplanner
    username: tourneeplanner
    password: tourneeplanner
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true